### ISSUE TITLE
建议添加一个从url中获取host的功能 

### ISSUE THREAD

**Issue by rainplus** [keelii/awesome-host-manager#1]
先给你点个赞，很好用。但我能不能添加一个类似hostswitch从url中获取host的功能 。。这个功能对分面式开发的人来说很好用的。谢谢！

**Comment by keelii** [comment]
@rainplus 你的意思是host回显示嘛？如果当前页面命中了host规则出个tips提示那种？

**Comment by rainplus** [comment]
@keelii  相当于swtichhost!的remote_host功能。 就是从url中获取host映射关系，保存的应用里面。定时更新

**Comment by ricoa** [comment]
就是读取网页的内容，当成host保存起来

**Comment by rainplus** [comment]
还要设置一个定时，或者点击再次获取
