### ISSUE TITLE
插件跟SwitchyOmega冲突

### ISSUE THREAD

**Issue by qianlifeng** [keelii/awesome-host-manager#2]
启用host-manager插件之后，SwitchyOmega显示如下消息：

>The proxy settings are controlled by other app(s) or extension(s). Please disable or uninstall the apps or extensions in conflict.
You cannot switch profiles with SwitchyOmega unless you fix the problem above.

能否禁用proxy功能？

**Comment by keelii** [comment]
@qianlifeng 这个是 chrome 的限制，有代理权限的插件只能使用一个。我之前用switchyOmega来fq的，不过我这个插件也支持 socket 代理的，如果你是用的 ss 翻墙那可以单独新建分组（见 README.md）switchyOmega就可以直接卸载/禁用了。如果你是重度 switchyOmega 用户，那这两个插件就只能二选一了，暂禁用另外一个。

**Comment by qianlifeng** [comment]
因为switchyOmega还有自定义的url list😢，所以暂时没办法禁用掉。
